DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    feed TEXT NOT NULL,
    title TEXT NOT NULL,
    date timestamp NOT NULL,
    link TEXT NOT NULL,
    content TEXT NOT NULL
);
